/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/root'
import { Route as errorDefaultErrorRoutesRouteImport } from './pages/error/default-error/routes'
import { Route as middlewaresPublicChatRouteImport } from './pages/middlewares/public-chat'
import { Route as error500RoutesRouteImport } from './pages/error/500/routes'
import { Route as error404RoutesRouteImport } from './pages/error/404/routes'
import { Route as error403RoutesRouteImport } from './pages/error/403/routes'
import { Route as indexRouteImport } from './pages/index'
import { Route as app_chatLayoutRouteImport } from './pages/app/(_chat)/layout'
import { Route as app_chatChatScreenRoutesRouteImport } from './pages/app/(_chat)/chat-screen/routes'

const errorDefaultErrorRoutesRoute = errorDefaultErrorRoutesRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const middlewaresPublicChatRoute = middlewaresPublicChatRouteImport.update({
  id: '/_public-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const error500RoutesRoute = error500RoutesRouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const error404RoutesRoute = error404RoutesRouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const error403RoutesRoute = error403RoutesRouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const app_chatLayoutRoute = app_chatLayoutRouteImport.update({
  id: '/_chat-layout',
  getParentRoute: () => middlewaresPublicChatRoute,
} as any)
const app_chatChatScreenRoutesRoute =
  app_chatChatScreenRoutesRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => app_chatLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '/403': typeof error403RoutesRoute
  '/404': typeof error404RoutesRoute
  '/500': typeof error500RoutesRoute
  '/error': typeof errorDefaultErrorRoutesRoute
  '/chat': typeof app_chatChatScreenRoutesRoute
}
export interface FileRoutesByTo {
  '/': typeof indexRoute
  '/403': typeof error403RoutesRoute
  '/404': typeof error404RoutesRoute
  '/500': typeof error500RoutesRoute
  '/error': typeof errorDefaultErrorRoutesRoute
  '/chat': typeof app_chatChatScreenRoutesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof indexRoute
  '/403': typeof error403RoutesRoute
  '/404': typeof error404RoutesRoute
  '/500': typeof error500RoutesRoute
  '/_public-chat': typeof middlewaresPublicChatRouteWithChildren
  '/error': typeof errorDefaultErrorRoutesRoute
  '/_public-chat/_chat-layout': typeof app_chatLayoutRouteWithChildren
  '/_public-chat/_chat-layout/chat': typeof app_chatChatScreenRoutesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/403' | '/404' | '/500' | '/error' | '/chat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/403' | '/404' | '/500' | '/error' | '/chat'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/404'
    | '/500'
    | '/_public-chat'
    | '/error'
    | '/_public-chat/_chat-layout'
    | '/_public-chat/_chat-layout/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute
  error403RoutesRoute: typeof error403RoutesRoute
  error404RoutesRoute: typeof error404RoutesRoute
  error500RoutesRoute: typeof error500RoutesRoute
  middlewaresPublicChatRoute: typeof middlewaresPublicChatRouteWithChildren
  errorDefaultErrorRoutesRoute: typeof errorDefaultErrorRoutesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof errorDefaultErrorRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public-chat': {
      id: '/_public-chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof middlewaresPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof error500RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof error404RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof error403RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public-chat/_chat-layout': {
      id: '/_public-chat/_chat-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof app_chatLayoutRouteImport
      parentRoute: typeof middlewaresPublicChatRoute
    }
    '/_public-chat/_chat-layout/chat': {
      id: '/_public-chat/_chat-layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof app_chatChatScreenRoutesRouteImport
      parentRoute: typeof app_chatLayoutRoute
    }
  }
}

interface app_chatLayoutRouteChildren {
  app_chatChatScreenRoutesRoute: typeof app_chatChatScreenRoutesRoute
}

const app_chatLayoutRouteChildren: app_chatLayoutRouteChildren = {
  app_chatChatScreenRoutesRoute: app_chatChatScreenRoutesRoute,
}

const app_chatLayoutRouteWithChildren = app_chatLayoutRoute._addFileChildren(
  app_chatLayoutRouteChildren,
)

interface middlewaresPublicChatRouteChildren {
  app_chatLayoutRoute: typeof app_chatLayoutRouteWithChildren
}

const middlewaresPublicChatRouteChildren: middlewaresPublicChatRouteChildren = {
  app_chatLayoutRoute: app_chatLayoutRouteWithChildren,
}

const middlewaresPublicChatRouteWithChildren =
  middlewaresPublicChatRoute._addFileChildren(
    middlewaresPublicChatRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  error403RoutesRoute: error403RoutesRoute,
  error404RoutesRoute: error404RoutesRoute,
  error500RoutesRoute: error500RoutesRoute,
  middlewaresPublicChatRoute: middlewaresPublicChatRouteWithChildren,
  errorDefaultErrorRoutesRoute: errorDefaultErrorRoutesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
